#!/usr/bin/env bash
# story of /etc/passwd

ISF=:
while read -r USERNAME PASSWORD USER_ID GROUP_ID_INFO HOME_DIRECTORY COMMAND_SHELL
do
	echo "The user $USERNAME is part of the GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND/SHELL. $USER ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER ID INFO"
done < /etc/passwd
