#!/usr/bin/env bash
# Bash script that gives you information about the school file

info=0
for file in *; do
    if [ "$file" == "school" ]
	then
	let info=1
	echo "school file exists"
	if [ -s "$file" ]
	    then
	    echo "school is not empty"

	else
	    echo "school is empty"
	fi
	if [ -f "$file" ]
	    then
	    echo "school file is a regular file"
	fi
    fi
done

if [ $info -eq 0 ]
    then
    echo "school file does not exist"
fi
