#!/usr/bin/env bash
# The script configures an Ubuntu server with the ff requirements

# 1. localhost resolves to 127.0.0.2
# 2. facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '2i8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
